// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsntuympgysgfgqdvzsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbnR1eW1wZ3lzZ2ZncWR2enNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzk4NzYsImV4cCI6MjA2OTkxNTg3Nn0.4PKYrz9P95Y37Z9iiZczRvaTIW63z0TUDrDKc8yTQwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});